config/routes.rb
Rails.application.routes.draw do

  resources :pickups
  resources :orders
  get 'bill_of_lading/address'

  get 'bill_of_lading/contract'

  get 'bill_of_lading/phone_number'

  resources :companies
  resources :invoices
  resources :drivers
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :vehicles
  resources :delivery_trucks

  get 'splash' => 'welcome#splash'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'consolepage' => 'welcome#consolepage'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'invoices' => 'invoice#index'

  get 'order_update' => 'invoice#order_update'

  get 'invoice' => 'invoice#invoice_form'

  get 'companies' => 'company#index'

  get 'contacts' => 'welcome#about'

  get 'dashboard' => 'welcome#index'

  get 'pickups' => 'pickup#index'

  get 'calendar' => 'welcome#calendar'

  get 'main' => 'welcome#about'

  get 'delivery_trucks_index' => 'delivery_trucks#index'

  get 'trucks' => 'delivery_trucks#index'

  get 'vehicles' => 'vehicles#index'

  get 'drivers' => 'drivers#index'

  get 'documents' => 'invoices#documents'

  get 'invoice_form' => 'invoices#_invoice_form'
  
  get 'bol' => 'invoices#_bol'

  root 'welcome#splash'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord

	def set_user!(user)
    self.user_id = user.id

    self.save!
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.where(user_id: current_user)
    @orders = Order.where(user_id: current_user)
    @user = current_user
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  def order_update
    respond_to do |format|
      if @order.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
    redirect_to root_path
  end

  def _bol
    @order = Order.find(params[:order_id])
    @user = User.where(params[:userId])
    @vehicle = Vehicle.where(params[:vehicle_id])
  end

  def _invoice_form
    @order = Order.find(params[:order_id])
    @user = User.where(params[:userId])
    @vehicle = Vehicle.where(params[:vehicle_id])
  end

  def documents
    @order = Order.find(params[:order_id])
    @user = User.where(params[:userId])
    @vehicle = Vehicle.where(params[:vehicle_id])
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:client, :truck_id, :userId, :total, :invoice_items, :dispatchdate)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(invoice) do |f| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :client, placeholder: "Client", autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.number_field :truck_id, placeholder: "Truck ID", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.number_field :userId, placeholder: "User ID", class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.text_field :total, placeholder: "Total", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_area :invoice_items, placeholder: "Invoice Items", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_field :dispatchdate, placeholder: "Dispatch Date", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.button "Submit" %>
  </div>
<% end %>

app/views/invoices/_invoice_form.html.erb
<ul class="nav nav-tabs">
  <% @order.order_items.each do |k,v| %>
    <li><a data-target="#inv<%= Vehicle.find(k).make %>" data-toggle="tab"><%= "#{Vehicle.find(k).make.capitalize} #{Vehicle.find(k).model.capitalize}" %></a></li>
  <% end %>
</ul>

  <div class="tab-content">

  <% first = true %>
  <% @order.order_items.each do |k,v| %>
    <% @vehicle = Vehicle.find(k) %>
    <% if first == true %>
        <div class="tab-pane active" id="<%= "inv#{Vehicle.find(k).make}" %>">
      <% first = false %>
    <% else %>
        <div class="tab-pane" id="<%= "inv#{Vehicle.find(k).make}" %>">
    <%end%>

  <div class="row">
  <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-6">
          <h1>Invoice</h1>
          <h1><small>Invoice #001</small></h1>
        </div>
        <div class="col-xs-6">
          <%= image_tag @vehicle.image %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>From: <a href="#"><%= current_user.username %></a></h4>
            </div>
            <div class="panel-body" style="height:150px;">
              <p>
                Address- <%= current_user.address %><br>
               
                more- <%= current_user.email %> <br>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-6 ">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>To : <a href="#">Client Name</a></h4>
            </div>
            <div class="panel-body" style="height:150px;">
              <p>
                Address- <%# address %><br>
                details- <%# details %> <br>
                more- <%# more info %> <br>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
      <div class="col-sm-12">
      <!-- / end client details section -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>
              <h4>Service</h4>
            </th>
            <th>
              <h4>Description</h4>
            </th>
            <th>
              <h4>Hrs/Qty</h4>
            </th>
            <th>
              <h4>Rate/Price</h4>
            </th>
            <th>
              <h4>Sub Total</h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Car Pick up</td>
            <td><a href="#">type of car or vehicle</a></td>
            <td class="text-right">-</td>
            <td class="text-right">$200.00 <%# desired invoice %></td>
            <td class="text-right">$200.00</td>
          </tr>
          <tr>
            <td>Multi Vehcile</td>
            <td><a href="#">Details of Vehicles</a></td>
            <td class="text-right">10</td>
            <td class="text-right">75.00</td>
            <td class="text-right">$750.00</td>
          </tr>
          <tr>
            <td>Drop Off's</td>
            <td><a href="#">info on drop offs</a></td>
            <td class="text-right">5</td>
            <td class="text-right">50.00</td>
            <td class="text-right">$250.00</td>
          </tr>
        </tbody>
      </table>
      </div>
      </div>
      <div class="row text-right">
        <div class="col-xs-2 col-xs-offset-8">
          <p>
            <strong>
            Sub Total : <%= number_to_currency @order.subtotal %> <br>
            TAX : <%= number_to_currency @order.sales_tax %> <br>
            Total : <%= number_to_currency @order.grand_total %> <br>
            </strong>
          </p>
        </div>
        <div class="col-xs-2">
          <strong>
          <%= number_to_currency @order.subtotal %><br>
         <br>
          N/A <br>
          <%= number_to_currency @order.grand_total %><br>
          </strong>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4>Bank details</h4>
            </div>
            <div class="panel-body">
              <p>Your Name: <%= current_user.username %></p>
              <p>Bank Name</p>
              <p>SWIFT : --------</p>
              <p>Account Number : --------</p>
              <p>IBAN : --------</p>
            </div>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="span7">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4>Contact Details</h4>
              </div>
              <div class="panel-body">
                <p>
                  Email :<%= current_user.email %> <br><br>
                  Mobile : <%= current_user.phone_number %><br> <br>
                  Company : <a href="https://"><%= current_user.username %> </a>
                </p>
                <h4>Payment should be made by Bank Transfer</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
<div class="row">
<div class="col-xs-12">
<select id="status" onChange="<% order_update_path %>">
  <option value="Paid">Paid</option>
  <option value="Unpaid">Unpaid</option>
  <option value="Archived">Archive</option>
</select>

    <ul>
        <li><%= "#{Vehicle.find(k).make} #{Vehicle.find(k).model}" %> <%= "#{v} Miles from #{Vehicle.find(k).origin} to #{Vehicle.find(k).destination}" %></li>
    </ul>

<p>
    <strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>
</div>
</div>
</div>
</div>
</div><%end%></div></div>

app/views/invoices/documents.html.erb
<div class="row">
  <div class="col-sm-2">
    <ul class="nav navbar-side">
      <li class="nav navbar navbar-nav"> <a data-target="#billoflading" data-toggle="tab">Bill of Lading</a></li>
      <li class="active nav navbar navbar-nav"> <a data-target="#thisinvoice" data-toggle="tab">Invoice</a></li>
    </ul>
  </div>
  <div class="col-sm-10">   
    <div class="tab-content" >
      <div class="tab-pane" id="billoflading" style="overflow: auto;">
        <%= render  'bol' %>
      </div>
      <div class="tab-pane active" id="thisinvoice"> 
        <%= render  'invoice_form' %>
      </div>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<div class="row">
  <div class="col-sm-2">
    <ul class="nav navbar-side">            
      <li class="active nav navbar navbar-nav"><a href="#home" data-target="#home" data-toggle="tab">Order History</a></li>
    </ul>
  </div>

  <div class="col-sm-10">
    <br />
    <h3>Invoices</h3>
    <table class="table-striped sortable autobox" style="width: 95%">
      <thead>
        <tr>
          <th width="10%">Invoice ID</th>
          <th>Created On</th>
          <th>Dispatch Date</th>
          <th>Order Total</th>
          <th>Truck ID</th>
          <th>Order Items</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.id, documents_path(:order_id => order.id ) %></td>
            <td><%= local_time(order.created_at) %></td>
            <td><%= order.dispatch_date %></td>
            <td><%= number_to_currency order.grand_total%></td>
            <td><%= order.truck_id %></td>
            <td><h5><a data-toggle="modal" data-target="#myModal<%=order.id%>" data-controls-modal="#myModal_<%=order.id%>" data-backdrop="static" data-keyboard="false" href="#"><span class="button"><%= "#{order.order_items.length} Vehicles" %></span></a></h5></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

<% @orders.each do |order| %>
  <div class="modal fade" id="myModal<%=order.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Loaded Vehicles</h4>
        </div>
        <div class="modal-body">
          <table class="table-striped sortable" width="100%">
            <thead>
                <th width="20%"><h4>Vehicle</h4></th>
                <th width="20%"><h4>Origin</h4></th>
                <th width="20%"><h4>Destination</h4></th>
                <th width="10%"><h4>Distance</h4></th>
                <th width="10%"><h4>Weight</h4></th>
                <th width="10%"><h4>Bid</h4></th>

            </thead>
            <tbody>  
            <%  order.order_items.each do |k,v| %>
            <tr>
              <td><%= "#{Vehicle.find(k).make.capitalize} #{Vehicle.find(k).model.capitalize}" %></td>
              <td><%= "#{Vehicle.find(k).origin.gsub(", United States", "")}" %></td>
              <td><%= "#{Vehicle.find(k).destination.gsub(", United States", "")}" %></td>
              <td><%= "#{Vehicle.find(k).distance}" %></td>
              <td><%= "#{Vehicle.find(k).actualWeight}"%></td>
              <td><%= "#{number_to_currency Vehicle.find(k).distance}" %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<div class="row">
  <div class="col-sm-2">
    <ul class="nav navbar-side">
      <li class="active nav navbar navbar-nav"> <a href="#billoflading" data-target="#billoflading" data-toggle="tab">Bill of Lading</a></li>
      <li class="nav navbar navbar-nav"> <a href="#invoicetab" data-target="#invoicetab" data-toggle="tab">Invoice  <br /> <br />   <br /> <br /></a></li>

      <li class="nav navbar navbar-nav"><i class="fa fa-tasks navbar-nav" style="padding-left:15px;"> 
        <%= link_to new_driver_path do %>  
        Add Driver
        <% end %>
      </i></li>
    </ul>
  </div>
    <div class="col-sm-10">
       <div class="tab-content"  >
          <div class="tab-pane active" id="billoflading"> 
            <% render  'bol', order_id: :order_id %>
          </div>
            <div class="tab-pane" id="invoicetab"> 
            <% render  'invoice_form', order_id: :order_id %>
            </div>
           </div></div></div> 