config/routes.rb
Rails.application.routes.draw do

  resources :pickups
  resources :orders
  get 'bill_of_lading/address'

  get 'bill_of_lading/contract'

  get 'bill_of_lading/phone_number'

  resources :companies
  resources :invoices
  resources :drivers
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :vehicles
  resources :delivery_trucks

  get 'splash' => 'welcome#splash'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'consolepage' => 'welcome#consolepage'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'invoices' => 'invoice#index'

  get 'order_update' => 'invoice#order_update'

  get 'invoice' => 'invoice#invoice_form'

  get 'companies' => 'company#index'

  get 'contacts' => 'welcome#about'

  get 'dashboard' => 'welcome#index'

  get 'pickups' => 'pickup#index'

  get 'calendar' => 'welcome#calendar'

  get 'main' => 'welcome#about'

  get 'delivery_trucks_index' => 'delivery_trucks#index'

  get 'trucks' => 'delivery_trucks#index'

  get 'vehicles' => 'vehicles#index'

  get 'drivers' => 'drivers#index'

  get 'documents' => 'invoices#documents'

  get 'invoice_form' => 'invoices#_invoice_form'
  
  get 'bol' => 'invoices#_bol'

  root 'welcome#splash'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/delivery_truck.rb
class DeliveryTruck < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :orders
	belongs_to :user


	def set_user!(user)
    self.user_id = user.id

    self.save!
  end
end

app/controllers/delivery_trucks_controller.rb
class DeliveryTrucksController < ApplicationController
  before_action :set_delivery_truck, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /delivery_trucks
  # GET /delivery_trucks.json
  def index
    @delivery_trucks = DeliveryTruck.where(user_id: current_user)
    @vehicles = Vehicle.all
  end 

  # GET /delivery_trucks/1
  # GET /delivery_trucks/1.json
  def show
    set_delivery_truck
    @myVehicles = Vehicle.where("truck_id LIKE ?", params[:id])
    @delivery_truck.update(occupied_slots: @myVehicles.length)
    @waypoints = Array.new
    @distances = Array.new
    @directions = Array.new
    @destination;

    @myVehicles.each do |vehicle|
      ##Include only one of each destination 
        @waypoints.push(vehicle.origin)
        @waypoints.push(vehicle.destination)
    end
    if @waypoints.empty?
    else
      ###Find furthest point for destination
      @waypoints.each do |wp|
        @directions.push GoogleDirections.new(@delivery_truck.origin, wp)
        @distances.push (@directions.last.distance_in_miles)
      end
      if @directions.any?
        @destination = @waypoints[@distances.index(@distances.max)]
      end
    end

  end
  # GET /delivery_trucks/new
  def new
    @delivery_truck = DeliveryTruck.new
  end

  # GET /delivery_trucks/1/edit
  def edit
  end

  # POST /delivery_trucks
  # POST /delivery_trucks.json
  def create
    @delivery_truck = DeliveryTruck.new(delivery_truck_params)
    @delivery_truck.update(currentState: "Available")
    @user = current_user
    @delivery_truck.set_user!(current_user)
    respond_to do |format|
      if @delivery_truck.save
        format.html { redirect_to @delivery_truck, notice: 'Delivery truck was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_truck }
      else
        format.html { render :new }
        format.json { render json: @delivery_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_trucks/1
  # PATCH/PUT /delivery_trucks/1.json
  def update
    respond_to do |format|
      if @delivery_truck.update(delivery_truck_params)
        format.js { render :js => "loadtables();" }

        format.html { redirect_to @delivery_truck, notice: 'Delivery truck was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_truck }
      else
        format.html { render :edit }
        format.json { render json: @delivery_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_trucks/1
  # DELETE /delivery_trucks/1.json
  def destroy
    @delivery_truck.destroy
    respond_to do |format|
      format.html { redirect_to delivery_trucks_url, notice: 'Delivery truck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_delivery_truck
    @delivery_truck = DeliveryTruck.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def delivery_truck_params
    params.require(:delivery_truck).permit(:name, :minimumPossibleWeight, :maximumPossibleWeight, :vinNumber, :origin, :destination, :yearManufactured, :make, :model, :payloadEmptyWeight, :originLocation, :currentLocation, :destinationLocation, :weightCapacity, :yearAquired, :carFax, :maintenanceHistory, :nextMaintenance, :highwayMPG, :cityMPG, :avgMPG, :scheduledDepartureTime, :estimatedArrivalTime, :requestedArrivalTime, :image, :currentState)
  end
end

app/helpers/delivery_trucks_helper.rb
module DeliveryTrucksHelper

	def getWaypoints
		
	end
end

app/views/delivery_trucks/_form.html.erb
<!-- Needs to be moved to CSS -->
<style>
.form-group {
  width:100%;
}
.form-control {
  width:90%;
}
th{
  width:50%;
}
</style>

<%= form_for(delivery_truck) do |f| %>
  <% if delivery_truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery_truck.errors.count, "error") %> prohibited this delivery_truck from being saved:</h2>

      <ul>
      <% delivery_truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br /> <br />

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2" style="text-align: center;">
      <div class="well shadow">
       <h1>New Delivery Truck</h1>
      <div class="row">
      <br />
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
        </div>

       <div class="form-group">
          <%= f.text_field :make, placeholder: "Make", class: "form-control"  %>
        </div>
     
       <div class="form-group">
          <%= f.text_field :model, placeholder: "Model", class: "form-control"  %>
        </div>
        
        <div class="form-group">
          <%= f.text_field :vinNumber, placeholder: "Vin Number", class: "form-control"  %>
        </div>
       
        </div>
        <div class="col-sm-6">
        <div class="form-group">
          <%= f.text_field :origin, placeholder: "Origin Location", class: "form-control", id: "searchTextField"   %>
        </div>
        <div class="form-group">
          <%= f.text_field :avgMPG, placeholder: "Avg MPG", class: "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.number_field :yearManufactured, placeholder: "Year Manufactured", class: "form-control"  %>
        </div>
       <div class="form-group">
          <%= f.text_field :weightCapacity, placeholder: "Weight Capacity", class: "form-control"  %>
        </div>
        </div>
        </div>

        <div class="field">
          <%= f.hidden_field :payloadEmptyWeight, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :originLocation, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= f.hidden_field :currentLocation, placeholder: "Current Location" %>
        </div>

        <div class="field">
          <%= f.hidden_field :destinationLocation, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :yearAquired, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :carFax, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :maintenanceHistory, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :nextMaintenance, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :highwayMPG, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :cityMPG, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :user_id, value: current_user.id, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= f.hidden_field :scheduledDepartureTime, placeholder: "Scheduled Departure Time" %>
        </div>

        <div class="field">
          <%= f.hidden_field :estimatedArrivalTime, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :requestedArrivalTime, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.hidden_field :currentState, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.hidden_field :driverId, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.hidden_field :occupied_slots, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.hidden_field :currentWeight, class: "form-control" %>
        </div>
        <div class="field">
          <%= f.hidden_field :minimumPossibleWeight, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :maximumPossibleWeight, class: "form-control"  %>
        </div>

        <div class="field">
          <%= f.hidden_field :destination, class: "form-control"  %>
        </div>
 
        <div class="actions" style="display:inline; float:right; padding-top: 5px; padding-right: 5%;">
          <%= f.button :Submit, class: "btn btn-success" %>
        </div>

        <i class= "btn btn-primary" style="display:inline; float:right; margin-top: 5px; margin-right: 5px;"><%= link_to 'Back', delivery_trucks_path %></i>

        <div class="form-group" style="text-align:left; ">
          <strong>Upload Vehicle Image: </strong>
          <%= f.file_field :image %>
        </div>
      
      </div>
    </div>
  </div>
<% end %>

app/views/delivery_trucks/_loadedform.erb
<%= form_for(vehicle, :remote => true,:authenticity_token => true) do |f| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.collection_select(:truck_id, DeliveryTruck.all, :id, :name, { :include_blank => "Available"},{:onChange => "javascript: this.form.button.click();", :class => "selectTruck", :style => "width: 125px;"}) %>
	<%= f.submit "Add to Cart", class: "btn btn-primary", id: "button"%>
<% end %>

app/views/delivery_trucks/_not_allowed.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>HEY! THIS IS FOR AUTHORIZED PERSONNEL ONLY!</H1>
		<p>
			<%= image_tag 'notallowed.gif', alt: "nuh uh uh" %>
		</p>
	</div>
</div>

app/views/delivery_trucks/edit.html.erb
<h1>Editing Delivery Truck</h1>

<%= render 'form', delivery_truck: @delivery_truck %>


<i class= "btn btn-primary"><%= link_to 'Show', @delivery_truck %></i>
<i class= "btn btn-primary"><%= link_to 'Back', 'javascript:history.go(-1);' %></i>

app/views/delivery_trucks/index.html.erb
<div class="row">
  <div class="col-sm-2">
    <ul class="nav navbar-side">
    <li class="active nav navbar navbar-nav" style="width: 85%; padding-left:10px">
      <i style="padding-left: 15px;"><%= link_to(image_tag("carHauler-btn.png", class: 'img-responsive'), new_delivery_truck_path,  :method => :get) %> 
      <%= link_to 'Add to Fleet', new_delivery_truck_path %></i>
    </li>
    </ul>
  </div>
  <div class="col-sm-10" >
    <br />
    <h3>Fleet Vehicles</h3>
      <table class="table-striped sortable autobox" style="width: 95%">
        <thead>
          <tr>
            <th>Delivery Truck</th>
            <th>Status</th>
            <th>Remaining Capacity</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @delivery_trucks.each do |truck| %>
            <% @newWeight = truck.weightCapacity.to_i %>
            <% @count = 0 %>
            <% @vehicles.each do |vehicle| %>
              <% if vehicle.truck_id.to_i == truck.id.to_i %>
                <% @count += 1 %>
                <% @newWeight -= vehicle.actualWeight.to_i %>
              <% end %>
              <% truck.update(currentWeight: @newWeight.to_i) %>
            <% end %>
            <tr>
              <td><%= link_to truck.name, truck %></td>
              <td><a data-toggle="modal" data-target="#myModal<%=truck.id%>" data-controls-modal="#myModal_<%=truck.id%>" data-backdrop="static" data-keyboard="false" href="#"><span class="button"><% if @count > 0 %><%= @count %><%= " Vehicles Pending" %><% else %>Ready<%end%></span></a></td>
              <td><%= @newWeight %></td>
              <td><select style="width:125px" onChange="if(this.selectedIndex!=0) self.location=this.options[this.selectedIndex].value">
                <option selected disabled>Load Vehicle</option>
                  <% @vehicles.each do |vehicle| %>
                <option value=<%= "/?truck_id=#{URI.escape(truck.id.to_s)}&carId=#{URI.escape(vehicle.id.to_s)}"%>><%= vehicle.name %></option>
                  <%end%>
              </select></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% @delivery_trucks.each do |truck|%>
  
  <!-- Modal -->
  <div class="modal fade" id="myModal<%=truck.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Pending Load Configuration</h4>
        </div>
        <div class="modal-body">
          <table class="table-striped sortable" width="100%">
            <thead>
                <th width="30%">Vehicle</th>
                <th width="25%">Weight</th>
                <th width="30%">Action</th>
                <th width="15%">Confirm Vehicle</th>
            </thead>
            <tbody>  
              </tr>
              <% @vehicles.each do |vehicle|%>
                <% if vehicle.truck_id.to_s == truck.id.to_s %>
                  <tr>
                    <td><h5><%= link_to vehicle.name, vehicle %></h5></td>
                    <td><h5><%= vehicle.actualWeight %></h5></td>
                    <td><%= render 'loadedform', vehicle: vehicle %></td>
                    <% time = Time.new %>
                       <%= form_tag add_to_cart_path, :remote => true do %>
                        <%= hidden_field_tag :vehicle_id, vehicle.id %>
                        <%= hidden_field_tag :bid_total, vehicle.distance.to_i %>
                        <%= hidden_field_tag :dispatch_date, (time.month.to_s+"/"+time.day.to_s + "/" +time.year.to_s) %>
                        <%= hidden_field_tag :order_id, (vehicle.truck_id.to_s+(time.year.to_s+time.month.to_s+time.day.to_s)).to_i %>
                        <%= hidden_field_tag :truck_id, vehicle.truck_id.to_s %>
                        <td><%= submit_tag "Add to Cart", class: "btn btn-primary" %></td>
                    <% end %>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" >Cancel Order</button>
           <%= link_to "Finalize Load", view_order_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
</div>
    
<% end %>

app/views/delivery_trucks/new.html.erb
<%= render 'form', delivery_truck: @delivery_truck %>


		<br/>		<br/>

app/views/delivery_trucks/show.html.erb
<% getWaypoints() %>
<div class="row">
  <div class="col-sm-2">
    <ul class="nav navbar-side">
      <li class="active"> <a data-target="#home" data-toggle="tab">Home</a></li>
      <li><a data-target="#routetab" data-toggle="tab">Route Details</a></li>
      <li><a data-target="#cargo" data-toggle="tab">Cargo Details</a></li>
    </ul>
  </div>
  <div class="col-sm-10" >
      <div class="tab-content">
        <div class="tab-pane active map" id="home" style="width: 97%;">
          <div class="autobox map" style="min-height: 350px; border-top-right-radius:10px; border-top-left-radius: 10px;">
            <div class="col-md-6">
              <table>
                <tr>
                  <td width="50%"><h2><%= "#{@delivery_truck.name}" %></h2></td>
                </tr>
                <tr>
                  <td><h4><%= @delivery_truck.yearManufactured %> <%= @delivery_truck.make %> <%= @delivery_truck.model %></h4></td>
                </tr>

                <tr>
                  <td><strong><%= "VIN: #{@delivery_truck.vinNumber}" %></strong></td>
                </tr>
                <tr>
                  <td>Located in <%= @delivery_truck.currentLocation %></td>
                  <td><%= @delivery_truck.weightCapacity %>Lb Capacity</td>
                </tr>

                <tr>
                  <td>Dispatch Date: <%= @delivery_truck.scheduledDepartureTime %></td>
                  <td>Gets <%= @delivery_truck.avgMPG %> MPG</td>
                </tr>
              </table>
            </div>
            <div class="col-md-6">
              <%= image_tag @delivery_truck.image, class: "tableimage" %>
            </div>
          </div>
  
          <div class="map" id="mapbox" style="border-bottom-left-radius: 10px; border-bottom-right-radius:10px;"><div class="map" id="routemap" style="width: 80%;"></div></div>
        </div>

        <div class="tab-pane" id="routetab" > 
          <div class="col-md-6">
            <div id="directions-panel"></div>
          </div>
        </div>

        <div class="tab-pane" id="cargo">
          <div class="col-sm-12">
            <div class="autobox">  
              <table class="table-striped" width="100%">
                <thead>
                  <th>Car Name</th>
                  <th>Origin</th>
                  <th>Destination</th>
                  <th>Miles</th>
                  <th>Bid</th>
                  <th>Profit </th>
                </thead>
                <tbody>
                  <% @myVehicles.each do |vehicle| %>
                    <tr>
                      <td><%= link_to "#{vehicle.yearManufactured} #{vehicle.make} #{vehicle.model}".split.map(&:capitalize).join(' '), vehicle %></td>
                      <td><%=vehicle.origin%></td>
                      <td><%=vehicle.destination%></td>
                      <td><%=vehicle.distance%></td>
                      <td>$<%=vehicle.distance%></td>
                      <td><%= (vehicle.distance-((vehicle.distance / @delivery_truck.avgMPG)*2.25))%></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

    
<div class="row">
  <div class="col-sm-2 col-sm-offset-10">
  <br />
    <h4 style="display:inline;"><%= link_to 'Edit ', edit_delivery_truck_path, class: "fa fa-pencil" %> </h4>
    <h5 style="display:inline;"> <i class="fa fa-arrow-left" aria-hidden="true"><%= link_to ' Back', delivery_trucks_path %></i></h5>
  </div>
</div>
</div>

<select hidden id="start">
    <option hidden selected><%= @delivery_truck.origin %></option>
</select>

<select hidden multiple id="waypoints">
  <% @waypoints.uniq do |wp| %>
    <% if wp == @delivery_truck.origin %>
    <% else %>
    <option hidden selected><%= wp %> </option> 
    <%end%>
  <% end %>
</select>

<select hidden id="end">
  <option hidden selected><%= @destination %> </option>
</select>