config/routes.rb
Rails.application.routes.draw do

  resources :pickups
  resources :orders
  get 'bill_of_lading/address'

  get 'bill_of_lading/contract'

  get 'bill_of_lading/phone_number'

  resources :companies
  resources :invoices
  resources :drivers
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :vehicles
  resources :delivery_trucks

  get 'splash' => 'welcome#splash'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'consolepage' => 'welcome#consolepage'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'invoices' => 'invoice#index'

  get 'order_update' => 'invoice#order_update'

  get 'invoice' => 'invoice#invoice_form'

  get 'companies' => 'company#index'

  get 'contacts' => 'welcome#about'

  get 'dashboard' => 'welcome#index'

  get 'pickups' => 'pickup#index'

  get 'calendar' => 'welcome#calendar'

  get 'main' => 'welcome#about'

  get 'delivery_trucks_index' => 'delivery_trucks#index'

  get 'trucks' => 'delivery_trucks#index'

  get 'vehicles' => 'vehicles#index'

  get 'drivers' => 'drivers#index'

  get 'documents' => 'invoices#documents'

  get 'invoice_form' => 'invoices#_invoice_form'
  
  get 'bol' => 'invoices#_bol'

  root 'welcome#splash'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
	mount_uploader :image, ImageUploader
  before_save :geocode_endpoints
  validates :yearManufactured, :make, :model, :vinNumber, :origin, :destination, presence: true
  


  def set_user!(user)
    self.user_id = user.id

    self.save!
  end

  private

  #To enable Geocoder to works with multiple locations
  def geocode_endpoints
      geocoded = Geocoder.search(:origin).first
      if geocoded
        self.origin_latitude = geocoded.latitude
        self.origin_longitude = geocoded.longitude
      end

      geocoded = Geocoder.search(:destination).first
      if geocoded
        self.destination_latitude = geocoded.latitude
        self.destination_longitude = geocoded.longitude
      end
  end

	def image_from_url(url)
    self.image = open(url)
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  after_action :checkState, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  require 'json'

 

  #Loads All Vehicles
  def index
   @vehicles = Vehicle.all
  end


  def show
      #Drives Google Map & Updates Vehicle Distance
      @waypoints = Array.new
      if @vehicle.origin.nil? || @vehicle.destination.nil?
      else
      directions = GoogleDirections.new(@vehicle.origin, @vehicle.destination)
      @vehicle.update(distance: directions.distance_in_miles)
      end
      @waypoints.push @vehicle.destination
  end

  #Method to check current state of vehicle (needs to be moved to helper or model)
  def checkState
      if @vehicle.truck_id == "" || @vehicle.truck_id == nil
        @vehicle.currentState = "Available"
      elsif @vehicle.currentState = "Available"
        @vehicle.currentState = "Queued"
      end
      @vehicle.save
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    @vehicle.currentState = "Available";
    @vehicle.save
  end

  # GET /vehicles/1/edit
  def edit 
  end

  
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @user = current_user
    @vehicle.set_user!(current_user)
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vehicle_params
    params.require(:vehicle).permit(:name, :make, :model, :details, :yearManufactured,:distance, :origin, :origin_latitude, :origin_longitude, :destination, :destination_latitude, :destination_longitude, :vinNumber, :minimumPossibleWeight, :maximumPossibleWeight, :actualWeight, :truck_id, :image, :remote_image_url, :customername, :currentState, :company_id, :user_id)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'gmaps-autocomplete-rails'



# Requires supporting files with custom matchers and macros, etc,
# in ./support/ and its subdirectories.
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each {|f| require f}

end

app/views/vehicles/_form.html.erb
<%= form_for(vehicle) do |f| %>
  
  <%= f.select :yearManufactured, (1990..(Date.today.year+1)).to_a, {}, :id => "years", :style => "float: left;" %>
  <%= f.select :make, "makes", {}, :id => "makes", :style => "float: left;"%>
  <%= f.select :model, "Model", {}, :id => "models", :style => "float: left;"%>
  <%= f.select :details, "Style", {}, :id => "styles", :style => "float: left;" %>

  <div class="field-group">
    <%= f.collection_select(:company_id, Company.all, :id, :companyName, { :include_blank => "Company"}) %>
  </div>
  <div class="field-group">
    <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>

  <div class="field-group">
    <%= f.text_field :origin, placeholder: "Origin", id: "searchTextField", class: "form-control" %>
  </div>
  
  <div class="field-group">
    <%= f.text_field :destination, placeholder: "Desination", id: "searchTextField2", class: "form-control" %>
  </div>

  <div class="field-group">
    <%= f.text_field :vinNumber, placeholder: "VIN", class: "form-control" %>
  </div>

  <div class="field-group">
    <%= f.hidden_field :minimumPossibleWeight %>
  </div>

  <div class="field-group">
    <%= f.hidden_field :maximumPossibleWeight %>
  </div>

  <div class="field-group">
    <%= f.hidden_field :actualWeight, placeholder: "Weight", :id => "weight" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :origin_latitude, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :origin_longitude, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :distance, class: "form-control",value: "#{@vehicle.distance}" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :destination_latitude, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :truck_id, class: "form-control" %>
  </div>

   <div class="field form-group">
   <%= f.hidden_field :remote_image_url, id: "details" %>
  </div>
 
  <div class="actions" style="float:right;">
    <%= f.submit class: "btn btn-success" %>
  </div>

   <i class = "btn btn-primary" style="float:right;margin-right:5px;">
<%= link_to 'Back', vehicles_path %></i>
  <br />
<% end %>

app/views/vehicles/_not_allowed.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>HEY! THIS IS FOR AUTHORIZED PERSONNEL ONLY!</H1>
		<p>
			<%= image_tag 'notallowed.gif', alt: "nuh uh uh" %>
		</p>
	</div>
</div>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<i class= "btn btn-primary"><%= link_to 'Show', @vehicle %></i>
<i class= "btn btn-primary"><%= link_to 'Back', 'javascript:history.go(-1);' %></i>

 

app/views/vehicles/index.html.erb
<div class="row">
  <div class="col-sm-2 no-float">
    <ul class="nav navbar-side">
      <li class="active nav navbar navbar-nav"> <a href="#home" data-target="#home" data-toggle="tab">Suggested Contracts</a></li>
      <li class="nav navbar navbar-nav"><a href="#maptab" data-target="#routetab" data-toggle="tab">List All Contracts</a></li>
      <li class="nav navbar navbar-nav"><a href="#cargo" data-target="#cargo" data-toggle="tab">Contracts By Location</a></li>
      <br><br>
      <li class="nav navbar navbar-nav" style="width: 85%; padding-left:10px"><i>
        <%= link_to(image_tag("carHauler-btn.png", class: 'img-responsive'), new_vehicle_path,  :method => :get) %>
        <%= link_to 'New Vehicle', new_vehicle_path %></i>
      </li>
    </ul>
  </div>
  <div class="col-sm-10 no-float">
    <div class="tab-content">
      <div class="tab-pane active" id="home"> 
      <h3>Vehicle Orders</h3>
        <table class="table-striped sortable autobox" style="width: 95%">
          <thead>
            <tr><th>Car Name</th>
            <th>Origin</th>
            <th>Destination</th>
            <th>Miles</th>
            <th>Bid</th></tr>
          </thead>
          <tbody>
            <% @vehicles.each do |vehicle| %>
            <% if vehicle.truck_id == 'nil' or vehicle.truck_id.empty? %>
              <tr>
                <td><%= link_to "#{vehicle.yearManufactured} #{vehicle.make} #{vehicle.model}".split.map(&:capitalize).join(' '), vehicle %></td>
                <td><%=vehicle.origin%></td>
                <td><%=vehicle.destination%></td>
                <td><%=vehicle.distance%></td>
                <td>$<%=vehicle.distance%></td>
              <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="tab-pane" id="routetab"> 
        <table class="table-striped sortable autobox" style="width: 95%">
          <thead>
            <tr><th>Car Name</th>
            <th>Origin</th>
            <th>Destination</th>
            <th>Miles</th>
            <th>Bid</th></tr>
          </thead>
          <tbody>
            <% @vehicles.each do |vehicle| %>
              <tr>
                <td><%= link_to "#{vehicle.yearManufactured} #{vehicle.make} #{vehicle.model}".split.map(&:capitalize).join(' '), vehicle %></td>
                <td><%=vehicle.origin%></td>
                <td><%=vehicle.destination%></td>
                <td><%=vehicle.distance%></td>
                <td>$<%=vehicle.distance%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <div class="tab-pane" id="cargo">  
    </div>
  </div>
    </div></div>
  <br />
  <br />
  <div class="row" margin-top="0px">
    <div class="col-sm-12">
      
    </div>
  </div>


</div>
</body>

app/views/vehicles/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <br/><br/><br/><br/>
		<div class="well shadow">	
			<h1 class="centerfy">New Vehicle</h1>
			<br />
			<%= render 'form', vehicle: @vehicle %> <br>
		</div>
	</div>
</div>
<br />
<br />

app/views/vehicles/show.html.erb
<body class= "bioRhyme">

   <p id="notice"><%= notice %></p>
<div class="container">
  <div class="row-fluid">
    <div class="span8 well">
      <ul class="nav nav-tabs">
        <li class="active"> <a href="#home" data-target="#home" data-toggle="tab">Home</a></li>
        <li><a href="#maptab" data-target="#routetab" data-toggle="tab">Route Details</a></li>
        <li><a href="#cargo" data-target="#cargo" data-toggle="tab">Contract Details</a></li>
      </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="home">
          <div class="col-md-6">
            <table width="100%">
              <tr>
                <td><h3><%= @vehicle.yearManufactured%> <%= @vehicle.make.capitalize  %> <%= @vehicle.model.capitalize  %></h3> Contact: <%= @vehicle.user.email %></td>
                </tr>
              <tr>
              <td>Pick-Up Location:</td>
                <td><%= @vehicle.origin %></td>
              </tr>
              <tr>
                <td>Destination:</td>
                <td><%= @vehicle.destination %></td>
                </tr>
              <tr>
                <td>VIN:</td>
                <td><%= @vehicle.vinNumber %></td>
                </tr>
              <td>Actual Weight:</td>
                <td><%= @vehicle.actualWeight %></td>
              </tr>
              <tr>
               <td>Distance</td>
                <td><%= @vehicle.distance %></td>
              </tr>
              <tr>
                <td><br /></td>
              </tr>
            </table>
            <br />
          </div>
          <div class="col-md-6">
            <%= image_tag @vehicle.image, class: "tableimage" %>
            </div>
      
        <div id="mapbox"><div id="routemap"></div></div>
        </div>
        <div class="tab-pane" id="routetab"> 
          <div class="col-md-6">
            <div id="directions-panel"></div>
          </div>
          <div class="tab-pane" id="cargo">  
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 col-sm-offset-10">
    <h3><%= link_to 'Back', delivery_trucks_path %></h3>
  </div>
</div>
<div class="wellnavtextpad">
  <%= link_to 'Edit', edit_vehicle_path(@vehicle), class: "" %>
  <%= link_to 'Destroy', @vehicle, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<%= link_to 'Back', vehicles_path, class: "btn btn-default" %>

<select hidden id="start">
    <option hidden selected><%= @vehicle.origin %></option>
</select>

<select hidden id="waypoints">
  <option hidden selected><%= @vehicle.destination %></option>
</select>

<select hidden id="end">
  <option hidden selected><%= @vehicle.destination %></option>
</select>

</body>