config/routes.rb
Rails.application.routes.draw do

  resources :pickups
  resources :orders
  get 'bill_of_lading/address'

  get 'bill_of_lading/contract'

  get 'bill_of_lading/phone_number'

  resources :companies
  resources :invoices
  resources :drivers
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :vehicles
  resources :delivery_trucks

  get 'splash' => 'welcome#splash'

  post 'add_to_cart' => 'cart#add_to_cart'

  get 'consolepage' => 'welcome#consolepage'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'invoices' => 'invoice#index'

  get 'order_update' => 'invoice#order_update'

  get 'invoice' => 'invoice#invoice_form'

  get 'companies' => 'company#index'

  get 'contacts' => 'welcome#about'

  get 'dashboard' => 'welcome#index'

  get 'pickups' => 'pickup#index'

  get 'calendar' => 'welcome#calendar'

  get 'main' => 'welcome#about'

  get 'delivery_trucks_index' => 'delivery_trucks#index'

  get 'trucks' => 'delivery_trucks#index'

  get 'vehicles' => 'vehicles#index'

  get 'drivers' => 'drivers#index'

  get 'documents' => 'invoices#documents'

  get 'invoice_form' => 'invoices#_invoice_form'
  
  get 'bol' => 'invoices#_bol'

  root 'welcome#splash'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
       can :manage, :all
    else
       can :read, :all
    end


    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	
  def set_user!(user)
    self.user_id = user.id

    self.save!
  end
end

app/models/delivery_truck.rb
class DeliveryTruck < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :orders
	belongs_to :user


	def set_user!(user)
    self.user_id = user.id

    self.save!
  end
end

app/models/driver.rb
class Driver < ApplicationRecord
	belongs_to :user
	mount_uploader :image, ImageUploader


  def set_user!(user)
    self.user_id = user.id

    self.save!
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord

	def set_user!(user)
    self.user_id = user.id

    self.save!
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :vehicle
	belongs_to :order
	belongs_to :truck
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	belongs_to :delivery_truck
	belongs_to :user

	serialize :order_items, Hash
end

app/models/pickup.rb
class Pickup < ApplicationRecord

	 def start_time
   	##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	has_many :orders
 	has_many :vehicles
 	has_many :delivery_trucks
 	has_many :drivers
 		
 		def admin?
    	role == "admin"
		end

		
		
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
	mount_uploader :image, ImageUploader
  before_save :geocode_endpoints
  validates :yearManufactured, :make, :model, :vinNumber, :origin, :destination, presence: true
  


  def set_user!(user)
    self.user_id = user.id

    self.save!
  end

  private

  #To enable Geocoder to works with multiple locations
  def geocode_endpoints
      geocoded = Geocoder.search(:origin).first
      if geocoded
        self.origin_latitude = geocoded.latitude
        self.origin_longitude = geocoded.longitude
      end

      geocoded = Geocoder.search(:destination).first
      if geocoded
        self.destination_latitude = geocoded.latitude
        self.destination_longitude = geocoded.longitude
      end
  end

	def image_from_url(url)
    self.image = open(url)
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  #Creates a line item from a vehicle
	def add_to_cart
	  line_item = LineItem.create(vehicle_id: params[:vehicle_id],bid_total: params[:bid_total], dispatch_date: params[:dispatch_date], order_id: params[:order_id], truck_id: params[:truck_id])
	  line_item.save
    vehicle = Vehicle.find(params[:vehicle_id])
    vehicle.update(currentState: "Queued")
    vehicle.save
	  redirect_to root_path
	end

  def view_order
  	@line_items = LineItem.all
  end

  #I dont think this works - was trying to update orders, need to refactor invoice/order system possibly rescaffold.
  def update 
    respond_to do |format|
      if @order.update(vehicle_params)
        format.html { redirect_to @order, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  #Finalizes order, destroys line items
  def checkout
    @line_items = LineItem.all
    @order = Order.create(user_id: current_user.id, subtotal: 0, driver_id: params[:driver_id], start_time: params[:start_time])

    @line_items.each do |line_item|
      @order.order_items[line_item.vehicle_id] = line_item.bid_total
      @order.subtotal += line_item.bid_total
      @order.truck_id = line_item.truck_id.to_i
      vehicle = Vehicle.find(line_item.vehicle_id)
      truck = DeliveryTruck.find(line_item.truck_id)
      vehicle.update(currentState: "Dispatched")
      truck.update(currentState: "Dispatched")
      vehicle.save
      truck.save
    end
    @order.currentState = "Unpaid"
    @order.sales_tax = @order.subtotal * 0.07
    @order.grand_total = @order.subtotal + @order.sales_tax
    @order.save


    LineItem.destroy_all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))
$LOAD_PATH.unshift(File.dirname(__FILE__))

require 'gmaps-autocomplete-rails'



# Requires supporting files with custom matchers and macros, etc,
# in ./support/ and its subdirectories.
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each {|f| require f}

end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head class="bioRhyme">
   
    

    <title>SpeediOS Logistics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['THIS_GOOGLE_API_KEY']%>&amp;libraries=places" defer>
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <% if current_page?(root_path) or current_page?('splash') %>
  <% else %>

<style>

.intro-header {
    text-align: center;
    color: #f8f8f8;
    background-size: cover;

}

.intro-message {
    position: relative;
    padding-top: 10%;
    padding-bottom: 10%;

}

.intro-message > h1 {
    margin: 0;
    text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
    font-size: 3.5em;
}
</style>


  <body class="bioRhyme" style="min-height: 1200px;">

<div class="container">
      <div class="jumbotron jumbotron-fluid intro-header intro-message" height:"200"><h1>SpeediOS</h1><h3 style="margin-top: 0px;">Fleet Management &amp; Logistics Suite</h3></div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Dashboard", dashboard_path, class: "navbar-brand black" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_page?(trucks_path)%>
          <li class="active">
            <%else%>
            <li>
              <%end%>
            <%= link_to "Trucks", trucks_path, class: "nav navbar navbar-nav"%> 
          </li>
          <% if current_page?(vehicles_path)%>
            <li class="active">
          <%else%>
            <li>
          <%end%>
          <%= link_to "Cars", vehicles_path, class: "nav navbar navbar-nav"%>
            </li>
        
           <% if current_page?(drivers_path)%>
            <li class="active">
          <%else%>
            <li>
          <%end%>
            <%= link_to "Drivers", drivers_path, class: "nav navbar navbar-nav" %>
          </li>
        <% if current_page?(companies_path)%>
            <li class="active">
          <%else%>
            <li>
          <%end%>
                <%= link_to "Companies", companies_path, class: "nav navbar navbar-nav" %>
            </li>

          <% if current_page?(invoices_path)%>
            <li class="active">
          <%else%>
            <li>
          <%end%>
          <%= link_to "Invoices", invoices_path, class: "nav navbar navbar-nav"%>
            </li>


          <% if current_page?(invoices_path)%>
            <li class="active">
          <%else%>
            <li>
          <%end%>
          <%= link_to "Calendar", calendar_path, class: "nav navbar navbar-nav"%>
            </li>

                      </ul>
        <!-- Don't need search bar yet //
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        -->

        <!-- Don't need second drop down yet
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
      </ul>
      -->
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><div class="navbartextpad nav navbar-nav navbar-right" style="color: #337ab7;">Hello <%= current_user.username %>!</div></li> 
            <li><%= link_to "Profile", edit_user_registration_path, class: "" %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-btn btn-danger" %></li>
          <% end %>
        </ul> 

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>
    <%= yield %>
    </div>
  </body>
   <% if current_page?(root_path) or current_page?('splash') %>
  <% else %>

  <footer>
        <div class="container" style="text-align: center;">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; SpeediOS 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
    <% end %>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <a href="<%= calendar.url_for_previous_view%>" style="padding-left:8px; padding-right: 8px;"><span class="fa fa-arrow-circle-left fa-2x"> </a>
    </span>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <a href="<%= calendar.url_for_next_view%>" style="padding-left:8px; padding-right: 8px;"><span class="fa fa-arrow-circle-right fa-2x"> </a>
    </span>
  </div>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <a href="<%= calendar.url_for_previous_view%>" style="padding-left:8px; padding-right: 8px;"><span class="fa fa-arrow-circle-left fa-2x"> </a>
    </span>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <a href="<%= calendar.url_for_next_view%>" style="padding-left:8px; padding-right: 8px;"><span class="fa fa-arrow-circle-right fa-2x"> </a>
    </span>
  </div>
<br />
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previouss'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>